In [3]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [11]:
import numpy as np
a=np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [13]:
a=np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [20]:
a=np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [23]:
a=np.arange(10,60,5).reshape(2,5)
a

array([[10, 15, 20, 25, 30],
       [35, 40, 45, 50, 55]])

In [46]:
a=np.array([[1,2,3],[4,5,6]])
print(a)
print(a[0,1],a[1,2])
print(a[0])
print(a[:,0])

[[1 2 3]
 [4 5 6]]
2 6
[1 2 3]
[1 4]


In [53]:
a=np.array([[3,-1,4],[1,5,-9]])
b=np.array([[2,4,-5,6],[-1,7,9,3],[3,2,-7,-2]])
np.dot(a,b)

array([[ 19,  13, -52,   7],
       [-30,  21, 103,  39]])

In [54]:
print([1,2,3]+[4,5,6])
print([1,2,3]*4)

[1, 2, 3, 4, 5, 6]
[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]


In [55]:
x=np.array([3,-4,1])
y=np.array([5,2,3])
print(x+10)
print(y*4)
print(x+y)
print(x*y)

[13  6 11]
[20  8 12]
[ 8 -2  4]
[15 -8  3]


In [56]:
a=np.array([[1,2,3],[4,5,6]])
print(a.ndim)
print(a.shape)
print(a.size)

2
(2, 3)
6


In [62]:
x = np.arange(10)
print(x[3])
print(x[:4])
print(x[4:])
print(x[4:8])

3
[0 1 2 3]
[4 5 6 7 8 9]
[4 5 6 7]


In [64]:
x=np.array([[0,1,2,3,4],[5,6,7,8,9]])
print(x[1,2])
print(x[:,2:])

7
[[2 3 4]
 [7 8 9]]


In [73]:
x=np.arange(0,50,10)
index=np.array([3,1,4])
print(x[index])
mask=np.array([True,False,False,True,False])
print(x[mask])

[30 10 40]
[ 0 30]


In [74]:
y=np.arange(10,20,2)
print(y)
mask=y>15
print(mask)
print(y[mask])
y[mask]=100
print(y)

[10 12 14 16 18]
[False False False  True  True]
[16 18]
[ 10  12  14 100 100]


In [69]:
from sklearn import datasets
iris=datasets.load_iris()
print(iris.filename)

C:\Users\osos1\anaconda3\lib\site-packages\sklearn\datasets\data\iris.csv


In [71]:
import numpy as np
iris_data=np.genfromtxt('C:\\Users\\osos1\\anaconda3\\lib\\site-packages\\sklearn\\datasets\\data\\iris.csv'
                        ,delimiter=",",skip_header=1)
print(iris_data)

[[5.1 3.5 1.4 0.2 0. ]
 [4.9 3.  1.4 0.2 0. ]
 [4.7 3.2 1.3 0.2 0. ]
 [4.6 3.1 1.5 0.2 0. ]
 [5.  3.6 1.4 0.2 0. ]
 [5.4 3.9 1.7 0.4 0. ]
 [4.6 3.4 1.4 0.3 0. ]
 [5.  3.4 1.5 0.2 0. ]
 [4.4 2.9 1.4 0.2 0. ]
 [4.9 3.1 1.5 0.1 0. ]
 [5.4 3.7 1.5 0.2 0. ]
 [4.8 3.4 1.6 0.2 0. ]
 [4.8 3.  1.4 0.1 0. ]
 [4.3 3.  1.1 0.1 0. ]
 [5.8 4.  1.2 0.2 0. ]
 [5.7 4.4 1.5 0.4 0. ]
 [5.4 3.9 1.3 0.4 0. ]
 [5.1 3.5 1.4 0.3 0. ]
 [5.7 3.8 1.7 0.3 0. ]
 [5.1 3.8 1.5 0.3 0. ]
 [5.4 3.4 1.7 0.2 0. ]
 [5.1 3.7 1.5 0.4 0. ]
 [4.6 3.6 1.  0.2 0. ]
 [5.1 3.3 1.7 0.5 0. ]
 [4.8 3.4 1.9 0.2 0. ]
 [5.  3.  1.6 0.2 0. ]
 [5.  3.4 1.6 0.4 0. ]
 [5.2 3.5 1.5 0.2 0. ]
 [5.2 3.4 1.4 0.2 0. ]
 [4.7 3.2 1.6 0.2 0. ]
 [4.8 3.1 1.6 0.2 0. ]
 [5.4 3.4 1.5 0.4 0. ]
 [5.2 4.1 1.5 0.1 0. ]
 [5.5 4.2 1.4 0.2 0. ]
 [4.9 3.1 1.5 0.2 0. ]
 [5.  3.2 1.2 0.2 0. ]
 [5.5 3.5 1.3 0.2 0. ]
 [4.9 3.6 1.4 0.1 0. ]
 [4.4 3.  1.3 0.2 0. ]
 [5.1 3.4 1.5 0.2 0. ]
 [5.  3.5 1.3 0.3 0. ]
 [4.5 2.3 1.3 0.3 0. ]
 [4.4 3.2 1.3 0.2 0. ]
 [5.  3.5 1

In [75]:
print("mean of {} is {}".format(iris.feature_names[0],iris_data[:,0].mean()))

mean of sepal length (cm) is 5.843333333333334
